In [2]:
import numpy as np

A = np.array([[56, 0, 4.4, 68],
            [1.2,104.0,52,8],
            [1.8, 135, 99, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [15]:
A.shape

(3, 4)

In [16]:
cal = A.sum(axis=0) # 파이썬아 세로로 더해줘
print(cal)

[ 59.  239.  155.4  76.9]


In [17]:
cal.shape

(4,)

In [18]:
percentage = 100*A/cal # (3,4) 행렬 A를 (1,4)로 나누기
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [14]:
percentage = 100*A/cal.reshape(1,4) # (3,4) 행렬 A를 (1,4)로 나누기
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [11]:
cal.reshape(1,4) # 차원이 이미 같긴하지만 차원을 확실히 해둬야

array([[ 59. , 239. , 155.4,  76.9]])

In [12]:
cal.shape

(4,)

In [13]:
p = A/cal
p

array([[0.94915254, 0.        , 0.02831403, 0.88426528],
       [0.02033898, 0.43514644, 0.33462033, 0.10403121],
       [0.03050847, 0.56485356, 0.63706564, 0.01170351]])